### ISSUE TITLE
Don't force bind DNS to IPv6, if it's disabled

### ISSUE THREAD

**Issue by rwjack** [safing/portmaster#1335]
**What happened**:
![image](https://github.com/safing/portmaster/assets/59068073/6c3d5dc2-cb15-4b84-a73e-841e355069d3)

**What did you expect to happen?**:
Portmaster to have a switch not to use IPv6, because it probably can't read my mind, that I'm the one that disabled IPv6.

**How did you reproduce it?**:
I disabled IPv6 on my Desktop's network interface.

**Comment by dhaavi** [comment]
You did not provide a lot of info here, but the most probable cause is that you haven't fully disabled IPv6. Please disable IPv6 globally and/or on all network adapters. Then, restart Portmaster.

**Comment by rwjack** [comment]
I can't believe I forgot to check if IPv6 was enabled before I opened this ticket. Previously I had disabled it using this playbook:

```yaml
---
- name: Disable ipv6 on Debian hosts
  hosts: all

  tasks:
    - name: Disable ipv6 now
      shell:
        cmd: >
          sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&
          sysctl -w net.ipv6.conf.default.disable_ipv6=1 &&
          sysctl -w net.ipv6.conf.lo.disable_ipv6=1

    - name: Modify /etc/sysctl.conf
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          net.ipv6.conf.all.disable_ipv6=1
          net.ipv6.conf.default.disable_ipv6=1
          net.ipv6.conf.lo.disable_ipv6=1
```

Although it must have re-enabled itself after an update or something...

Ran the playbook again, restarted portmaster, no warning now.
Guess we can close this one out, thank you.
