### ISSUE TITLE
compatible report : AdguardHome and portmaster Compatible

### ISSUE THREAD

**Issue by ghost** [safing/portmaster#1436]
this very similiar to 
https://github.com/safing/portmaster/issues/364#issuecomment-895770278

For adguarhome  

open **AdGuardHome.yaml** 
and edit list line  
```
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
```
to
```
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53000
```
only edit port! 

them at protmaster put dns://127.0.0.1:53000 and dns://::1:53000 (*btw ipv6 just optional)

this will remove red notice if AdguardHome not compatible with protmaster
